# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LiveDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for LiveDemo

    pod 'FFmpeg', '~> 2.8.3'
    pod 'GPUImage', '~> 0.1.7'
    pod 'ijkplayer', '~> 1.1.2'
#    pod 'ReactiveCocoa', '~> 7.2.0'
    pod 'ReactiveObjC', '~> 3.1.0'
    pod 'Masonry', '~> 1.1.0'
# pod 'libx264-iOS', '~> 1.4'
# pod 'librtmp-iOS', '~> 1.1.0'




  target 'LiveDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
